name: peony_project
channels: 
  - conda-forge
  - anaconda
dependencies:
  - python == 3.7.0
  - tqdm
  - pandas
  - scikit-learn 
  - nltk
  - pip:
      - pymongo
      - black
      - matplotlib
      - -e .
