name: peony_project
channels: 
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python == 3.7.0
  - numpy
  - scipy
  - docker-compose 
  - tqdm
  - pandas
  - scikit-learn 
  - nltk
  - jupyter
  - pytorch
  - tensorflow
  - multiprocess
  - mkl-service
  - theano
  - pymc3
  - jax
  - seaborn
  - pip:
      - pymongo
      - black
      - matplotlib
      - numpyro
      - bert-serving-server
      - bert-serving-client
      - git+https://github.com/MFreidank/pysgmcmc@pytorch
      - -e .
