name: peony_project
channels: 
  - anaconda
  - pytorch
dependencies:
  - python == 3.7.0
  - numpy
  - scipy
  - docker-compose 
  - tqdm
  - pandas
  - scikit-learn 
  - nltk
  - jupyter
  - pytorch
  - tensorflow
  - multiprocess
  - theano
  - seaborn
  - dash
  - plotly
  - chart-studio
  - pip:
      - pymongo
      - spacy
      - black
<<<<<<< Updated upstream
      - matplotlib==3.2
      - numpyro
=======
      - matplotlib
>>>>>>> Stashed changes
      - bert-serving-server
      - bert-serving-client
      - git+https://github.com/MFreidank/pysgmcmc@pytorch
      - -e .
